{% set name = "getmail6" %}
{% set version = "6.19.08" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f0e00a679b21d274179418f8f931defa92352d92fa3a8ad651d0de6b5e93ae77

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [win]

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
    - getmail --help
    - getmail_fetch --help
    - getmail_maildir --help
    - getmail_mbox --help
    - getmail-gmail-xoauth-tokens --help

about:
  home: https://getmail6.org/
  summary: based on getmail 5.14, with adaptations for python 3
  description: |
    getmail6 is a flexible, extensible mail retrieval system with support 
    for POP3, IMAP4, SSL variants of both, maildirs, mboxrd files, 
    external MDAs, arbitrary message filtering, single-user and 
    domain-mailboxes, and many other useful features.
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: docs/COPYING
  doc_url: https://getmail6.org/
  dev_url: https://github.com/getmail6/getmail6

extra:
  recipe-maintainers:
    - jan-janssen
